// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Discover Legal

// Renderers — one structured MatterStatusReport, three outputs: machine-readable
// JSON (for downstream signal harvesting), human Markdown, and a DOCX stakeholder
// update. All three read the same object, so the human and machine views can
// never drift.
package lpm

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/discover-legal/biglaw-go/internal/types"
)

// RenderJSON returns the indented machine-readable form.
func RenderJSON(r *types.MatterStatusReport) ([]byte, error) {
	return json.MarshalIndent(r, "", "  ")
}

// RenderMarkdown returns a human-readable status update.
func RenderMarkdown(r *types.MatterStatusReport) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Matter Status — %s\n\n", orDash(r.MatterNumber))
	fmt.Fprintf(&b, "*%s · health %.0f/100 (%s%s) · confidence %.0f%%*\n\n",
		r.Date, r.HealthScore, orDash(r.HealthSignal), trendSuffix(r.HealthTrend), r.Confidence*100)

	if r.BLUF != "" {
		fmt.Fprintf(&b, "**Bottom line:** %s\n\n", r.BLUF)
	}
	if r.Summary != "" {
		b.WriteString("## Summary\n\n" + r.Summary + "\n\n")
	}

	if len(r.Workstreams) > 0 {
		b.WriteString("## Workstreams\n\n")
		for _, w := range r.Workstreams {
			fmt.Fprintf(&b, "- **%s** (%s)", w.Name, orDash(w.Status))
			if w.NextStep != "" {
				fmt.Fprintf(&b, " — next: %s", w.NextStep)
			}
			if w.Owner != "" {
				fmt.Fprintf(&b, " — owner: %s", w.Owner)
			}
			if w.DueDate != "" {
				fmt.Fprintf(&b, " — due: %s", w.DueDate)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if len(r.Risks) > 0 {
		b.WriteString("## Risks\n\n")
		for _, rk := range r.Risks {
			fmt.Fprintf(&b, "- **[%s]** %s", strings.ToUpper(rk.Severity), rk.Description)
			if rk.RecommendedAction != "" {
				fmt.Fprintf(&b, " → %s", rk.RecommendedAction)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	if len(r.OpenQuestions) > 0 {
		b.WriteString("## Open questions\n\n")
		for _, q := range r.OpenQuestions {
			fmt.Fprintf(&b, "- %s\n", q)
		}
		b.WriteString("\n")
	}

	d := r.Deltas
	b.WriteString("## Since last report\n\n")
	fmt.Fprintf(&b, "- %d new task(s), %d closed, %d new finding(s)\n", d.NewTasks, d.ClosedTasks, d.NewFindings)
	fmt.Fprintf(&b, "- %d email(s) routed to this matter\n", d.EmailsRouted)
	fmt.Fprintf(&b, "- %.1fh logged ($%.2f)\n\n", d.HoursLogged, d.BilledUsd)

	b.WriteString("---\n")
	b.WriteString("*Generated by Big Michael · CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGE*\n")
	return b.String()
}

// RenderDOCX returns a .docx stakeholder update built from the report.
func RenderDOCX(r *types.MatterStatusReport) ([]byte, error) {
	d := &docxBuilder{}
	d.Heading(1, "Matter Status — "+orDash(r.MatterNumber))
	d.Para(fmt.Sprintf("%s  ·  health %.0f/100 (%s%s)  ·  confidence %.0f%%",
		r.Date, r.HealthScore, orDash(r.HealthSignal), trendSuffix(r.HealthTrend), r.Confidence*100))

	if r.BLUF != "" {
		d.Heading(2, "Bottom line")
		d.Para(r.BLUF)
	}
	if r.Summary != "" {
		d.Heading(2, "Summary")
		d.Para(r.Summary)
	}

	if len(r.Workstreams) > 0 {
		d.Heading(2, "Workstreams")
		for _, w := range r.Workstreams {
			line := w.Name + " (" + orDash(w.Status) + ")"
			if w.NextStep != "" {
				line += " — next: " + w.NextStep
			}
			if w.Owner != "" {
				line += " — owner: " + w.Owner
			}
			if w.DueDate != "" {
				line += " — due: " + w.DueDate
			}
			d.Bullet(line)
		}
	}

	if len(r.Risks) > 0 {
		d.Heading(2, "Risks")
		for _, rk := range r.Risks {
			line := "[" + strings.ToUpper(rk.Severity) + "] " + rk.Description
			if rk.RecommendedAction != "" {
				line += " → " + rk.RecommendedAction
			}
			d.Bullet(line)
		}
	}

	if len(r.OpenQuestions) > 0 {
		d.Heading(2, "Open questions")
		for _, q := range r.OpenQuestions {
			d.Bullet(q)
		}
	}

	dl := r.Deltas
	d.Heading(2, "Since last report")
	d.Bullet(fmt.Sprintf("%d new task(s), %d closed, %d new finding(s)", dl.NewTasks, dl.ClosedTasks, dl.NewFindings))
	d.Bullet(fmt.Sprintf("%d email(s) routed to this matter", dl.EmailsRouted))
	d.Bullet(fmt.Sprintf("%.1fh logged ($%.2f)", dl.HoursLogged, dl.BilledUsd))

	d.Para("")
	d.Para("Generated by Big Michael · CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGE")
	return d.Bytes()
}

func trendSuffix(trend string) string {
	switch trend {
	case "improving":
		return ", ↑"
	case "declining":
		return ", ↓"
	default:
		return ""
	}
}
