// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Discover Legal
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version. See <https://www.gnu.org/licenses/>.

/**
 * DocuSeal tools — electronic signature for generated legal documents.
 *
 * DocuSeal (https://www.docuseal.com) is a fully open-source, self-hostable
 * e-signature platform (MIT licence).
 *
 * Self-host: docker run -d -p 3000:3000 docuseal/docuseal
 * API key:   Settings → API in the DocuSeal admin panel.
 *
 * Three tools:
 *   docuseal_list_templates   — list available templates (for template reuse)
 *   docuseal_send_for_signing — upload a PDF, create template + submission, return signing URLs
 *   docuseal_submission_status — check whether all parties have signed
 *
 * Typical agent workflow:
 *   1. pdf_generate        → produces /path/to/brief.pdf
 *   2. docuseal_send_for_signing(path, signers) → signing URLs per party
 *   3. docuseal_submission_status(id)  → check status / get signed PDF URL
 */

import { readFile, stat } from "fs/promises";
import { basename, resolve, sep } from "path";
import { Config } from "../config.js";
import { logger } from "../logger.js";
import { assertPublicHttpUrl } from "../settings/index.js";
import type { ToolImpl } from "./index.js";
import { assertSafeReadPath } from "./pdf.js";

// ─── SSRF validation at startup ───────────────────────────────────────────────
if (Config.docuseal.url && Config.docuseal.url !== "http://localhost:3000") {
  try {
    assertPublicHttpUrl(Config.docuseal.url, "DOCUSEAL_URL");
  } catch (err) {
    logger.warn("DocuSeal URL validation failed — DocuSeal disabled", { error: (err as Error).message });
  }
}

// ─── Shared HTTP helper ───────────────────────────────────────────────────────

async function docusealFetch(
  method: "GET" | "POST" | "DELETE",
  path: string,
  body?: unknown,
): Promise<unknown> {
  const url = `${Config.docuseal.url}${path}`;
  const headers: Record<string, string> = {
    "X-Auth-Token": Config.docuseal.apiKey,
  };

  let reqBody: BodyInit | undefined;
  if (body instanceof FormData) {
    reqBody = body; // multipart — let fetch set Content-Type with boundary
  } else if (body !== undefined) {
    headers["Content-Type"] = "application/json";
    reqBody = JSON.stringify(body);
  }

  const res = await fetch(url, { method, headers, body: reqBody });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`DocuSeal ${method} ${path} failed (${res.status}): ${text.slice(0, 400)}`);
  }

  return res.json();
}

// ─── docuseal_list_templates ──────────────────────────────────────────────────

export const docusealListTemplatesTool: ToolImpl = {
  name: "docuseal_list_templates",
  schema: {
    name: "docuseal_list_templates",
    description:
      "List available DocuSeal signing templates. " +
      "Use this to find an existing template ID before calling docuseal_send_for_signing.",
    input_schema: {
      type: "object" as const,
      properties: {
        limit: { type: "number", description: "Maximum templates to return (default 20)" },
      },
    },
  },
  async execute(input, _ctx) {
    if (!Config.docuseal.enabled || !Config.docuseal.apiKey) {
      return { warning: "DOCUSEAL_API_KEY not configured — DocuSeal unavailable", templates: [] };
    }
    const limit = Math.max(1, Math.min(100, Math.floor((input.limit as number | undefined) ?? 20)));
    const data = await docusealFetch("GET", `/api/templates?limit=${limit}`) as { data: unknown[] };
    return { templates: data.data ?? data };
  },
};

// ─── docuseal_send_for_signing ────────────────────────────────────────────────

export const docusealSendForSigningTool: ToolImpl = {
  name: "docuseal_send_for_signing",
  schema: {
    name: "docuseal_send_for_signing",
    description:
      "Send a legal document for electronic signing via DocuSeal. " +
      "Either upload a PDF from a local path (generated by pdf_generate) or reference " +
      "an existing template by ID. Returns a submission ID and per-signer signing URLs.",
    input_schema: {
      type: "object" as const,
      properties: {
        pdfPath: {
          type: "string",
          description: "Absolute path to the PDF file to send for signing (from pdf_generate output).",
        },
        templateId: {
          type: "number",
          description: "Existing DocuSeal template ID (alternative to uploading a new PDF).",
        },
        documentName: {
          type: "string",
          description: "Human-readable name for the document, e.g. 'Mutual NDA 2026'.",
        },
        signers: {
          type: "array",
          description: "List of parties who must sign. At least one required.",
          items: {
            type: "object",
            properties: {
              role: { type: "string", description: "Signer role, e.g. 'Client', 'Counsel', 'Counterparty'" },
              name: { type: "string", description: "Signer's full name" },
              email: { type: "string", description: "Signer's email address" },
            },
          },
        },
        sendEmail: {
          type: "boolean",
          description: "Whether DocuSeal should email signing links directly. Default false (return URLs instead).",
        },
        message: {
          type: "string",
          description: "Optional custom message included in the signing invitation email.",
        },
      },
      required: ["signers"],
    },
  },
  async execute(input, _ctx) {
    if (!Config.docuseal.enabled || !Config.docuseal.apiKey) {
      return {
        warning: "DOCUSEAL_API_KEY not configured — DocuSeal unavailable",
        submissionId: null,
        signingUrls: [],
      };
    }

    let templateId = input.templateId as number | undefined;
    const signers = (input.signers as Array<unknown>).slice(0, 50) as Array<{ role: string; name: string; email: string }>;
    const sendEmail = (input.sendEmail as boolean | undefined) ?? false;
    const documentName = (input.documentName as string | undefined) ?? "Legal Document";

    // ── Upload PDF as new template if no templateId provided ─────────────
    if (!templateId) {
      const pdfPath = input.pdfPath as string | undefined;
      if (!pdfPath) {
        throw new Error("Either pdfPath or templateId must be provided");
      }

      const safePath = assertSafeReadPath(pdfPath);
      logger.debug("Uploading PDF to DocuSeal", { pdfPath: safePath });

      const MAX_FILE_BYTES = 100 * 1024 * 1024; // 100 MB
      const fileStats = await stat(safePath);
      if (fileStats.size > MAX_FILE_BYTES) {
        throw new Error(`File too large: ${fileStats.size} bytes (max ${MAX_FILE_BYTES})`);
      }

      const bytes = await readFile(safePath);
      const form = new FormData();
      form.append("name", documentName);
      form.append(
        "file",
        new Blob([bytes], { type: "application/pdf" }),
        basename(safePath),
      );

      const tmpl = await docusealFetch("POST", "/api/templates", form) as { id: number };
      templateId = tmpl.id;
      logger.debug("DocuSeal template created", { templateId });
    }

    // ── Create submission ─────────────────────────────────────────────────
    const submission = await docusealFetch("POST", "/api/submissions", {
      template_id: templateId,
      send_email: sendEmail,
      message: input.message,
      submitters: signers.map((s) => ({
        role: s.role ?? "Signer",
        name: s.name,
        email: s.email,
      })),
    }) as {
      id: number;
      slug: string;
      status: string;
      submitters: Array<{
        id: number;
        name: string;
        email: string;
        role: string;
        status: string;
        embed_src?: string;
      }>;
    };

    logger.info("DocuSeal submission created", {
      submissionId: submission.id,
      status: submission.status,
      signers: submission.submitters.length,
    });

    return {
      submissionId: submission.id,
      status: submission.status,
      templateId,
      signingLinks: submission.submitters.map((s) => ({
        name: s.name,
        email: s.email,
        role: s.role,
        status: s.status,
        signingUrl: s.embed_src ?? null,
      })),
    };
  },
};

// ─── docuseal_submission_status ───────────────────────────────────────────────

export const docusealSubmissionStatusTool: ToolImpl = {
  name: "docuseal_submission_status",
  schema: {
    name: "docuseal_submission_status",
    description:
      "Check the signing status of a DocuSeal submission. " +
      "Returns per-signer status and, when fully signed, the URL of the completed document.",
    input_schema: {
      type: "object" as const,
      properties: {
        submissionId: {
          type: "number",
          description: "DocuSeal submission ID returned by docuseal_send_for_signing",
        },
      },
      required: ["submissionId"],
    },
  },
  async execute(input, _ctx) {
    if (!Config.docuseal.enabled || !Config.docuseal.apiKey) {
      return { warning: "DOCUSEAL_API_KEY not configured — DocuSeal unavailable" };
    }

    const id = input.submissionId as number;
    if (!Number.isInteger(id) || id <= 0) throw new Error("submissionId must be a positive integer");
    const data = await docusealFetch("GET", `/api/submissions/${id}`) as {
      id: number;
      status: string;
      submitters: Array<{
        name: string;
        email: string;
        role: string;
        status: string;
        completed_at?: string;
      }>;
      documents?: Array<{ name: string; url: string }>;
      completed_at?: string;
    };

    const allSigned = data.submitters.every((s) => s.status === "completed");

    return {
      submissionId: data.id,
      status: data.status,
      allSigned,
      completedAt: data.completed_at ?? null,
      signers: data.submitters.map((s) => ({
        name: s.name,
        email: s.email,
        role: s.role,
        status: s.status,
        completedAt: s.completed_at ?? null,
      })),
      signedDocuments: data.documents ?? [],
    };
  },
};
